services:
  assistant:
    build: assistant
    environment:
      ASSISTANT_LANGUAGES: ${ASSISTANT_LANGUAGES}
      SYSTEM_PROMPT_en: ${SYSTEM_PROMPT_en}
      RAG_PROMPT_en: ${RAG_PROMPT_en}
      RAGLESS_PROMPT_en: ${RAGLESS_PROMPT_en}
      SYSTEM_PROMPT_sw: ${SYSTEM_PROMPT_sw}
      RAG_PROMPT_sw: ${RAG_PROMPT_sw}
      RAGLESS_PROMPT_sw: ${RAGLESS_PROMPT_sw}
      SYSTEM_PROMPT_fr: ${SYSTEM_PROMPT_fr}
      RAG_PROMPT_fr: ${RAG_PROMPT_fr}
      RAGLESS_PROMPT_fr: ${RAGLESS_PROMPT_fr}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_QUEUE_USER_CHATS: ${RABBITMQ_QUEUE_USER_CHATS}
      RABBITMQ_QUEUE_USER_CHAT_REPLIES: ${RABBITMQ_QUEUE_USER_CHAT_REPLIES}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_CHAT_MODEL: ${OPENAI_CHAT_MODEL}
      CHROMADB_HOST: ${CHROMADB_HOST}
      CHROMADB_PORT: ${CHROMADB_PORT}
      CHROMADB_COLLECTION_TEMPLATE: ${CHROMADB_COLLECTION_TEMPLATE}
      CHROMADB_DISTANCE_CUTOFF: ${CHROMADB_DISTANCE_CUTOFF}
    depends_on:
      - rabbitmq
      - chromadb

  eppo-librarian:
    build: eppo-librarian
    environment:
      EPPO_COUNTRY_ORGANISM_URL: ${EPPO_COUNTRY_ORGANISM_URL}
      EPPO_DATASHEET_URL: ${EPPO_DATASHEET_URL}
      EPPO_COUNTRIES: ${EPPO_COUNTRIES}
      ASSISTANT_LANGUAGES: ${ASSISTANT_LANGUAGES}
      CHROMADB_HOST: ${CHROMADB_HOST}
      CHROMADB_PORT: ${CHROMADB_PORT}
      CHROMADB_COLLECTION_TEMPLATE: ${CHROMADB_COLLECTION_TEMPLATE}
      CHUNK_SIZE: ${CHUNK_SIZE}
      OVERLAP_SIZE: ${OVERLAP_SIZE}
    depends_on:
      - chromadb
    restart: no

  chromadb:
    image: chromadb/chroma:0.5.5
    ports:
      - ${CHROMADB_PORT}:${CHROMADB_PORT}
    environment:
      IS_PERSISTENT: True
      ANONYMIZED_TELEMETRY: False
    volumes:
      - ./chromadb-data:/chroma/chroma

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia/

  postgres:
    image: postgres:12-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/script:/script:ro
      - ./pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.6
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    environment:
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      PGADMIN_DEFAULT_EMAIL: dev@akvo.org
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./postgres/pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pg-admin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build: backend
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_EXCHANGE_USER_CHATS: ${RABBITMQ_EXCHANGE_USER_CHATS}
      RABBITMQ_QUEUE_USER_CHATS: ${RABBITMQ_QUEUE_USER_CHATS}
      RABBITMQ_QUEUE_USER_CHAT_REPLIES: ${RABBITMQ_QUEUE_USER_CHAT_REPLIES}
      DATABASE_URL: postgresql://akvo:${POSTGRES_PASS}@postgres:${POSTGRES_PORT}/dev
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      WEBDOMAIN: "${WEBDOMAIN}:${FRONTEND_PORT}"
      MAGIC_LINK_CHAT_TEMPLATE: ${MAGIC_LINK_CHAT_TEMPLATE}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    depends_on:
      - postgres
      - rabbitmq

