CREATE USER akvo WITH CREATEDB PASSWORD '${POSTGRES_PASS}';

CREATE DATABASE dev
WITH OWNER = akvo
     TEMPLATE = template0
     ENCODING = 'UTF8'
     LC_COLLATE = 'en_US.UTF-8'
     LC_CTYPE = 'en_US.UTF-8';

CREATE DATABASE dev_test
WITH OWNER = akvo
     TEMPLATE = template0
     ENCODING = 'UTF8'
     LC_COLLATE = 'en_US.UTF-8'
     LC_CTYPE = 'en_US.UTF-8';
