"""alter unique constraint of phone number and client name

Revision ID: 33e313a32ce6
Revises: 88850c0758b4
Create Date: 2024-09-17 04:16:14.656177

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "33e313a32ce6"
down_revision: Union[str, None] = "88850c0758b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "client_properties_name_key", "client_properties", type_="unique"
    )
    op.create_unique_constraint(
        "unique_client_name", "client_properties", ["client_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_client_name", "client_properties", type_="unique"
    )
    op.create_unique_constraint(
        "client_properties_name_key", "client_properties", ["name"]
    )
    # ### end Alembic commands ###
