"""Add status column into chat table

Revision ID: cfc217bbdd23
Revises: 33e313a32ce6
Create Date: 2024-09-24 07:18:13.207997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "cfc217bbdd23"
down_revision: Union[str, None] = "33e313a32ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column("status", sa.Integer(), nullable=True),
    )
    op.execute("UPDATE chat SET status = 1")
    op.alter_column("chat", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "status")
    # ### end Alembic commands ###
