"""Remove server_default from created_at columm in chat table

Revision ID: 68926921afdf
Revises: f5a9dc155fe8
Create Date: 2024-11-05 03:33:33.294291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "68926921afdf"
down_revision: Union[str, None] = "f5a9dc155fe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat", "created_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat", "created_at", server_default=sa.func.now())
    # ### end Alembic commands ###
